# Generated by Django 6.0.3 on 2026-04-07 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=6)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_conversation',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='rating',
            new_name='customer_rating',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='review_count',
            new_name='customer_reviews',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='conversation',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='myproject.job'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('job_request', 'Job Request'), ('job_accepted', 'Job Accepted'), ('job_declined', 'Job Declined'), ('job_completed', 'Job Completed')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='worker_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='worker_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending Approval'), ('taken', 'Taken'), ('done', 'Done')], default='open', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user_one', 'user_two', 'job'), name='unique_conversation_per_job'),
        ),
    ]
