# Generated by Django 6.0.3 on 2026-04-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_pendingsignup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer_trust',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='worker_trust',
            field=models.FloatField(default=0),
        ),
    ]
